### ISSUE TITLE
when it will be available

### ISSUE THREAD

**Issue by naah69** [SkyAPM/skywalking-python#1]
when it will be available

**Comment by wu-sheng** [comment]
I don't know no one is working on this. Sorry. We are looking forward to new volunteer.

**Comment by naah69** [comment]
sorry,i am not good at Py.
i will use py Recently
i will try to write pt-agent when i can do it

**Comment by u20024804** [comment]
If skywalking supports opentracing, can I just use opentracing-python as a skywalking agent?
Or what should I do if I need to write a skywalking python agent based on opentracing-python?

**Comment by wu-sheng** [comment]
OpenTracing has nothing related to. our implementation. It is just a API layer, that is all. So, the thing we need is a native python agent for SkyWalking protocol.

**Comment by u20024804** [comment]
Can I use some Zipkin python agent because skywalking can receive Zipkin trace?

**Comment by wu-sheng** [comment]
It wouldn't work with other agents. @kezhenxu94 is working on the native python agent. So, be patient, it has a chance to release 2-3 months later.
